update cleaner

diff --git a/bin/.local/bin/cleaner b/bin/.local/bin/cleaner
--- a/bin/.local/bin/cleaner
+++ b/bin/.local/bin/cleaner
@@ -3,6 +3,7 @@
 magenta='\e[1;35m'
 red='\e[1;31m'
 white='\e[0;37m'
+dry_run=false
 
 shopt -s extglob
 
@@ -22,109 +23,171 @@ Usage: $program_name [-option]
 
 Options:
     --help    Print this message
-    -s        Safe cleaner, except browser and image thumbnails
-    -a        Clean all junk folders and files
+    --dry-run Print commands without running them
+    -s        Clean user caches and junk files
+    -a        Clean user caches, junk files, and thumbnails
+    -L        Clean selected system logs
+    --system-logs
+              Clean selected system logs
 EOF
 }
 
-safe_cleaner() {
+run() {
+    if "$dry_run"; then
+        printf '+'
+        printf ' %q' "$@"
+        printf '\n'
+    else
+        "$@"
+    fi
+}
+
+truncate_file() {
+    local file="$1"
+
+    if "$dry_run"; then
+        printf '+ : > %q\n' "$file"
+    else
+        : > "$file"
+    fi
+}
+
+truncate_system_file() {
+    local file="$1"
+
+    if "$dry_run"; then
+        printf '+ sudo sh -c %q\n' ": > $file"
+    else
+        sudo sh -c ": > '$file'"
+    fi
+}
+
+confirm() {
+    local message="$1"
+    local response
+
+    read -r -p "$message [y/N] " response
+    case "$response" in
+        [yY]|[yY][eE][sS])
+            return 0
+            ;;
+        *)
+            echo "Cancelled."
+            return 1
+            ;;
+    esac
+}
+
+clean_user_files() {
     echo -e "$magenta\n Cleaning Debian Packages... \n$white"
-    sudo apt clean
+    run sudo apt clean
 
     echo -e "$magenta\n Autocleaning Debian Packages... \n$white"
-    sudo apt autoclean
+    run sudo apt autoclean
 
     echo -e "$magenta\n Autoremoving Debian Packages... \n$white"
-    sudo apt autoremove
+    run sudo apt autoremove
 
     echo -e "$magenta\n Cleaning Composer Installer... \n$white"
-    rm -fv ~/.local/share/composer/20*.phar
+    run rm -fv ~/.local/share/composer/20*.phar
 
     echo -e "$magenta\n Cleaning Gems... \n$white"
-    gem cleanup
+    run gem cleanup
 
     echo -e "$magenta\n Cleaning Shell History... \n$white"
-    echo > ~/.bash_history && echo > ~/.zsh_history && echo > ~/.z && rm -fv ~/.z.*
+    truncate_file "$HOME/.bash_history"
+    truncate_file "$HOME/.zsh_history"
+    truncate_file "$HOME/.z"
+    run rm -fv ~/.z.*
 
     echo -e "$magenta\n Cleaning Cache... \n$white"
-    rm -rfv ~/.cache/!(chromium|composer|fontconfig|mozilla|pnpm|thumbnails|thunderbird)
+    run rm -rfv ~/.cache/!(chromium|composer|fontconfig|mozilla|pnpm|thumbnails|thunderbird)
 
     echo -e "$magenta\n Cleaning Junk Files... \n$white"
-    rm -rfv ~/.local/share/Trash/*
-    rm -fv ~/.local/share/recently-used.xbel
-    rm -fv ~/.lesshst
-    rm -fv ~/.{node_repl,php,python,units}_history
-    rm -fv ~/.wget-hsts
-    rm -fv ~/.xsession-errors*
+    run rm -rfv ~/.local/share/Trash/*
+    run rm -fv ~/.local/share/recently-used.xbel
+    run rm -fv ~/.lesshst
+    run rm -fv ~/.{node_repl,php,python,units}_history
+    run rm -fv ~/.wget-hsts
+    run rm -fv ~/.xsession-errors*
 
     echo -e "$magenta\n Cleaning Editor... \n$white"
-    rm -rfv ~/.local/share/nano/search_history
-    rm -rfv ~/.local/share/nvim/backup/*
-    rm -rfv ~/.local/share/nvim/shada/*
-    rm -rfv ~/.local/share/nvim/swap/*
-    rm -rfv ~/.local/share/nvim/undo/*
-    rm -rfv ~/.config/sublime-text-3/Cache/* &> /dev/null
-    rm -rfv ~/.config/sublime-text-3/Index/*
-    rm -rfv ~/.config/sublime-text-3/Local/*.sublime_session
-    rm -fv ~/.viminfo
+    run rm -rfv ~/.local/share/nano/search_history
+    run rm -rfv ~/.local/share/nvim/backup/*
+    run rm -rfv ~/.local/share/nvim/shada/*
+    run rm -rfv ~/.local/share/nvim/swap/*
+    run rm -rfv ~/.local/share/nvim/undo/*
+    run rm -rfv ~/.config/sublime-text-3/Cache/*
+    run rm -rfv ~/.config/sublime-text-3/Index/*
+    run rm -rfv ~/.config/sublime-text-3/Local/*.sublime_session
+    run rm -fv ~/.viminfo
+}
+
+clean_thumbnails() {
+    echo -e "$magenta\n Cleaning Thumbnails... \n$white"
+    run rm -rfv ~/.cache/thumbnails/*
+    run rm -rfv ~/.thumbnails/*
+}
+
+clean_system_logs() {
+    if ! "$dry_run"; then
+        confirm "This will truncate selected system logs. Continue?" || return 0
+    fi
 
     echo -e "$magenta\n Cleaning Log System... \n$white"
-    sudo sh -c "echo > /var/log/alternatives.log"
-    sudo sh -c "echo > /var/log/dpkg.log"
-    sudo sh -c "echo > /var/log/lastlog"
-    sudo sh -c "echo > /var/log/maillog"
-    sudo sh -c "echo > /var/log/messages"
-    sudo sh -c "echo > /var/log/secure"
-    sudo sh -c "echo > /var/log/wtmp"
-    sudo sh -c "echo > /var/log/xferlog"
 
-    sudo rm -rfv /var/log/apt/*.log
-    sudo rm -rfv /var/log/lightdm/*.log
-    sudo rm -rfv /var/log/lightdm/*.log.1.gz
-    sudo rm -rfv /var/log/lightdm/*.old
-    sudo rm -rfv /var/log/mysql/*.gz
-    sudo rm -rfv /var/log/mysql/*.log
-    sudo rm -rfv /var/log/nginx/*.log.1
-    sudo rm -rfv /var/log/postgresql/*.log
-    sudo rm -rfv /var/log/postgresql/*.log.1
-
-    sudo rm -rfv /var/log/*.old &> /dev/null
-    sudo rm -rfv /var/log/*.0 &> /dev/null
-    sudo rm -rfv /var/log/*.1 &> /dev/null
-    sudo rm -rfv /var/log/*.2 &> /dev/null
-    sudo rm -rfv /var/log/*.3 &> /dev/null
-    sudo rm -rfv /var/log/*.gz &> /dev/null
-
-    sudo rm -rfv /var/log/apt/*.old &> /dev/null
-    sudo rm -rfv /var/log/apt/*.0 &> /dev/null
-    sudo rm -rfv /var/log/apt/*.1 &> /dev/null
-    sudo rm -rfv /var/log/apt/*.2 &> /dev/null
-    sudo rm -rfv /var/log/apt/*.3 &> /dev/null
-    sudo rm -rfv /var/log/apt/*.gz &> /dev/null
+    run sudo journalctl --vacuum-time=7d
+    truncate_system_file /var/log/alternatives.log
+    truncate_system_file /var/log/dpkg.log
+    truncate_system_file /var/log/lastlog
+    truncate_system_file /var/log/wtmp
 }
 
 main() {
-    case "$1" in
-        ''|-h|--help)
-            usage
-            exit 0
-            ;;
-        -s)
-            sudo echo -e "$red\n Executing a safe cleaner. \n$white"
-            safe_cleaner
-            ;;
-        -a)
-            sudo echo -e "$red\n Executing a whole cleaner. \n$white"
-            safe_cleaner
-            echo -e "$magenta\n Cleaning Thumbnails... \n$white"
-            rm -rfv ~/.cache/thumbnails/*
-            rm -rfv ~/.thumbnails/*
-            ;;
-        *)
-            echo "Command not found"
-            exit 1
-            ;;
-    esac
+    local clean_user=false
+    local clean_thumb=false
+    local clean_logs=false
+
+    if [ "$#" -eq 0 ]; then
+        usage
+        exit 0
+    fi
+
+    while [ "$#" -gt 0 ]; do
+        case "$1" in
+            -h|--help)
+                usage
+                exit 0
+                ;;
+            --dry-run)
+                dry_run=true
+                ;;
+            -s)
+                clean_user=true
+                ;;
+            -a)
+                clean_user=true
+                clean_thumb=true
+                ;;
+            -L|--system-logs)
+                clean_logs=true
+                ;;
+            *)
+                echo "Command not found: $1"
+                exit 1
+                ;;
+        esac
+        shift
+    done
+
+    if "$dry_run"; then
+        echo -e "$red\n Executing in dry-run mode. \n$white"
+    fi
+
+    "$clean_user" && clean_user_files
+    "$clean_thumb" && clean_thumbnails
+    "$clean_logs" && clean_system_logs
+    return 0
 }
 
 main "$@"
