update

diff --git a/bin/.local/bin/update-beauty b/bin/.local/bin/update-beauty
--- a/bin/.local/bin/update-beauty
+++ b/bin/.local/bin/update-beauty
@@ -5,6 +5,11 @@ green='\e[1;32m'
 red='\e[0;31m'
 white='\e[0;37m'
 source_dir="$HOME/.local/src"
+dry_run=false
+assume_yes=false
+update_all=false
+update_commands=("update_oh-my-zsh" "update_i3" "update_i3blocks"
+                 "update_i3lock" "update_rofi" "update_dunst" "update_picom")
 
 # Since some programs are installed in non-root directories,
 # don't run this script as root to avoid permission conflict.
@@ -22,11 +27,82 @@ Usage: $program_name [-option]
 
 Options:
     --help    Print this message
-    -a        Update all packages
+    -n, --dry-run
+              Print commands without running them
+    -y, --yes Skip confirmation prompts
+    -a        Update all packages, with per-package confirmation
 EOF
 }
 
 # Tools.
+parse_args() {
+    while [ "$#" -gt 0 ]; do
+        case "$1" in
+            -h|--help)
+                usage
+                exit 0
+                ;;
+            -n|--dry-run)
+                dry_run=true
+                ;;
+            -y|--yes)
+                assume_yes=true
+                ;;
+            -a)
+                update_all=true
+                ;;
+            *)
+                echo "Command not found: $1"
+                exit 1
+                ;;
+        esac
+        shift
+    done
+}
+
+run() {
+    if "$dry_run"; then
+        printf '+'
+        printf ' %q' "$@"
+        printf '\n'
+    else
+        "$@"
+    fi
+}
+
+confirm() {
+    local message="$1"
+    local response
+
+    "$assume_yes" && return 0
+    read -r -p "$message [y/N] " response
+    case "$response" in
+        [yY]|[yY][eE][sS])
+            return 0
+            ;;
+        *)
+            echo "Cancelled."
+            return 1
+            ;;
+    esac
+}
+
+confirm_install() {
+    local component="$1"
+
+    "$dry_run" && return 0
+    confirm "Install $component into system paths with sudo?"
+}
+
+confirm_git_clean() {
+    echo -e "$magenta\n Files that would be removed by git clean: \n$white"
+    run git clean -fdn
+
+    "$dry_run" && return 0
+    confirm "Remove these untracked files?" || return 1
+    run git clean -fd
+}
+
 row() {
     seq -s '─' 0 "$(tput cols)" | tr -d '[:digit:]'
 }
@@ -51,9 +127,9 @@ use_latest_release() {
     local get_version
     get_version=$(get_latest_release)
     if [ -n "$get_version" ]; then
-        git clean -fd
-        git fetch origin tag "$get_version" --no-tags || return 1
-        git checkout "$get_version"
+        confirm_git_clean || return 1
+        run git fetch origin tag "$get_version" --no-tags || return 1
+        run git checkout "$get_version"
     else
         echo -e "${red}[!] Error: There is an internet connection issue.${white}"
         return 1
@@ -63,38 +139,42 @@ use_latest_release() {
 # Installer.
 update_oh-my-zsh() {
     echo -e "$magenta\n Updating oh-my-zsh... \n$white"
-    zsh "$HOME/.oh-my-zsh/tools/upgrade.sh"
+    run zsh "$HOME/.oh-my-zsh/tools/upgrade.sh"
     echo -e "$magenta\n Updating zsh plugins... \n$white"
-    cd "$HOME/.zsh/plugins" || return
-    find . -mindepth 1 -maxdepth 1 -type d -print -exec git -C {} pull \;
+    cd "$HOME/.oh-my-zsh/custom/plugins" || return
+    while IFS= read -r plugin_dir; do
+        echo "$plugin_dir"
+        run git -C "$plugin_dir" pull
+    done < <(find . -mindepth 1 -maxdepth 1 -type d -print)
 }
 
 update_i3() {
     echo -e "$magenta\n Updating & compiling i3... \n$white"
     cd "$source_dir/i3" || return
-    rm -rf build
+    run rm -rf build
     use_latest_release || return 1
-    mkdir build
-    meson --buildtype=release . build
-    ninja -C build
+    run mkdir build
+    run meson --buildtype=release . build
+    run ninja -C build
     echo -e "$green\n Previous i3 version: \n$white"
     row
     i3 -v
     row
     echo -e "$magenta\n Installing i3... \n$white"
-    sudo install -Dm755 --verbose build/i3 /usr/bin/i3
-    sudo install -Dm755 --verbose build/i3bar /usr/bin/i3bar
-    sudo install -Dm755 --verbose build/i3-config-wizard /usr/bin/i3-config-wizard
-    sudo install -Dm755 --verbose build/i3-dump-log /usr/bin/i3-dump-log
-    sudo install -Dm755 --verbose build/i3-input /usr/bin/i3-input
-    sudo install -Dm755 --verbose build/i3-msg /usr/bin/i3-msg
-    sudo install -Dm755 --verbose build/i3-nagbar /usr/bin/i3-nagbar
-    sudo install -Dm755 --verbose i3-dmenu-desktop /usr/bin/i3-dmenu-desktop
-    sudo install -Dm755 --verbose i3-migrate-config-to-v4 /usr/bin/i3-migrate-config-to-v4
-    sudo install -Dm755 --verbose i3-save-tree /usr/bin/i3-save-tree
-    sudo install -Dm755 --verbose i3-sensible-editor /usr/bin/i3-sensible-editor
-    sudo install -Dm755 --verbose i3-sensible-pager /usr/bin/i3-sensible-pager
-    sudo install -Dm755 --verbose i3-sensible-terminal /usr/bin/i3-sensible-terminal
+    confirm_install "i3" || return 1
+    run sudo install -Dm755 --verbose build/i3 /usr/bin/i3
+    run sudo install -Dm755 --verbose build/i3bar /usr/bin/i3bar
+    run sudo install -Dm755 --verbose build/i3-config-wizard /usr/bin/i3-config-wizard
+    run sudo install -Dm755 --verbose build/i3-dump-log /usr/bin/i3-dump-log
+    run sudo install -Dm755 --verbose build/i3-input /usr/bin/i3-input
+    run sudo install -Dm755 --verbose build/i3-msg /usr/bin/i3-msg
+    run sudo install -Dm755 --verbose build/i3-nagbar /usr/bin/i3-nagbar
+    run sudo install -Dm755 --verbose i3-dmenu-desktop /usr/bin/i3-dmenu-desktop
+    run sudo install -Dm755 --verbose i3-migrate-config-to-v4 /usr/bin/i3-migrate-config-to-v4
+    run sudo install -Dm755 --verbose i3-save-tree /usr/bin/i3-save-tree
+    run sudo install -Dm755 --verbose i3-sensible-editor /usr/bin/i3-sensible-editor
+    run sudo install -Dm755 --verbose i3-sensible-pager /usr/bin/i3-sensible-pager
+    run sudo install -Dm755 --verbose i3-sensible-terminal /usr/bin/i3-sensible-terminal
     echo -e "$green\n Current i3 version: \n$white"
     row
     i3 -v
@@ -105,65 +185,69 @@ update_i3blocks() {
     echo -e "$magenta\n Updating & compiling i3blocks... \n$white"
     cd "$source_dir/i3blocks" || return
     use_latest_release || return 1
-    autoreconf -fi
-    ./configure
-    make
+    run autoreconf -fi
+    run ./configure
+    run make
     echo -e "$green\n Previous i3blocks version: \n$white"
     row
     i3blocks -V
     row
     echo -e "$magenta\n Installing i3blocks... \n$white"
-    sudo make install
+    confirm_install "i3blocks" || return 1
+    run sudo make install
     echo -e "$green\n Current i3blocks version: \n$white"
     row
     i3blocks -V
     row
     echo -e "$magenta\n Updating i3blocks-contrib... \n$white"
     cd "$source_dir/i3blocks-contrib" || return
-    git pull
+    run git pull
 }
 
 update_i3lock() {
     echo -e "$magenta\n Updating & compiling i3lock... \n$white"
     cd "$source_dir/i3lock-color" || return
-    rm -rf build
+    run rm -rf build
     use_latest_release || return 1
-    autoreconf -i
-    mkdir build
+    run autoreconf -i
+    run mkdir build
     cd build || return
-    ../configure --enable-debug=no --disable-sanitizers
-    make
+    run ../configure --enable-debug=no --disable-sanitizers
+    run make
     echo -e "$green\n Previous i3lock version: \n$white"
     row
     i3lock -v
     row
     echo -e "$magenta\n Installing i3lock... \n$white"
-    sudo make install
+    confirm_install "i3lock" || return 1
+    run sudo make install
     echo -e "$green\n Current i3lock version: \n$white"
     row
     i3lock -v
     row
     echo -e "$magenta\n Updating i3lock-fancy... \n$white"
     cd "$source_dir/i3lock-fancy" || return
-    git pull
-    sudo make install
+    run git pull
+    confirm_install "i3lock-fancy" || return 1
+    run sudo make install
 }
 
 update_rofi() {
     echo -e "$magenta\n Updating & compiling rofi... \n$white"
     cd "$source_dir/rofi" || return
-    rm -rf build
+    run rm -rf build
     use_latest_release || return 1
-    git submodule update --init
-    mkdir build
-    meson --buildtype=release . build
-    ninja -C build
+    run git submodule update --init
+    run mkdir build
+    run meson --buildtype=release . build
+    run ninja -C build
     echo -e "$green\n Previous rofi version: \n$white"
     row
     rofi -v
     row
     echo -e "$magenta\n Installing rofi... \n$white"
-    sudo install -Dm755 --verbose build/rofi /usr/local/bin/rofi
+    confirm_install "rofi" || return 1
+    run sudo install -Dm755 --verbose build/rofi /usr/local/bin/rofi
     echo -e "$green\n Current rofi version: \n$white"
     row
     rofi -v
@@ -173,16 +257,17 @@ update_rofi() {
 update_dunst() {
     echo -e "$magenta\n Updating & compiling dunst... \n$white"
     cd "$source_dir/dunst" || return
-    make clean
+    run make clean
     use_latest_release || return 1
-    make WAYLAND=0
-    make dunstify
+    run make WAYLAND=0
+    run make dunstify
     echo -e "$green\n Previous dunst version: \n$white"
     row
     dunst -v
     row
     echo -e "$magenta\n Installing dunst... \n$white"
-    sudo make install
+    confirm_install "dunst" || return 1
+    run sudo make install
     echo -e "$green\n Current dunst version: \n$white"
     row
     dunst -v
@@ -192,17 +277,18 @@ update_dunst() {
 update_picom() {
     echo -e "$magenta\n Updating & compiling picom... \n$white"
     cd "$source_dir/picom" || return
-    rm -rf build
+    run rm -rf build
     use_latest_release || return 1
-    git submodule update --init
-    meson --buildtype=release . build -Dwith_docs=false
-    ninja -C build
+    run git submodule update --init
+    run meson --buildtype=release . build -Dwith_docs=false
+    run ninja -C build
     echo -e "$green\n Previous picom version: \n$white"
     row
     picom --version
     row
     echo -e "$magenta\n Installing picom... \n$white"
-    sudo install -Dm755 --verbose build/src/picom /usr/local/bin/picom
+    confirm_install "picom" || return 1
+    run sudo install -Dm755 --verbose build/src/picom /usr/local/bin/picom
     echo -e "$green\n Current picom version: \n$white"
     row
     picom --version
@@ -210,15 +296,17 @@ update_picom() {
 }
 
 update_one_by_one() {
-    declare -a arr=("update_oh-my-zsh" "update_i3" "update_i3blocks"
-                    "update_i3lock" "update_rofi" "update_dunst" "update_picom")
+    local update_command
+    local response
 
-    for update_command in "${arr[@]}"; do
+    for update_command in "${update_commands[@]}"; do
         echo
         read -r -p "Do you want to ${update_command//_/ }? [y/n] " response
         case $response in
             [yY][eE][sS]|[yY])
-                $update_command
+                if ! $update_command; then
+                    echo -e "${red}[!] ${update_command} failed or was skipped.${white}"
+                fi
                 ;;
             *)
                 echo "Cancelled."
@@ -227,29 +315,30 @@ update_one_by_one() {
     done
 }
 
+update_all_packages() {
+    local update_command
+
+    for update_command in "${update_commands[@]}"; do
+        if "$assume_yes" || confirm "Run ${update_command//_/ }?"; then
+            if ! $update_command; then
+                echo -e "${red}[!] ${update_command} failed or was skipped.${white}"
+            fi
+        fi
+    done
+}
+
 main() {
-    case "$1" in
-        -h|--help)
-            usage
-            exit 0
-            ;;
-        '')
-            update_one_by_one
-            ;;
-        -a)
-            update_oh-my-zsh
-            update_i3
-            update_i3blocks
-            update_i3lock
-            update_rofi
-            update_dunst
-            update_picom
-            ;;
-        *)
-            echo "Command not found"
-            exit 1
-            ;;
-    esac
+    parse_args "$@"
+
+    if "$dry_run"; then
+        echo -e "$red\n Executing in dry-run mode. \n$white"
+    fi
+
+    if "$update_all"; then
+        update_all_packages
+    else
+        update_one_by_one
+    fi
 }
 
 main "$@"
